[package]
name = "lumi-cli"
version = "0.1.0"
edition = "2021"
autobins = false

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
lumi-parser = { path = "../parser" }
lumi-typer  = { path = "../typer" }
lumi-ir     = { path = "../ir" }
lumi-codegen-wasm = { path = "../codegen-wasm" }

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
tempfile = "3"
wasmtime = "15"
wasmparser = "0.219"

[[bin]]
name = "lumi"
path = "src/main.rs"
