[package]
name = "clg-typer"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
clg-ast = { path = "../ast" }
clg-ir  = { path = "../ir" }
anyhow = "1"

[dev-dependencies]
clg-parser = { path = "../parser" }
criterion = "0.5"

[[bench]]
name = "typer"
harness = false
